# Generated by Django 5.1 on 2024-08-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_permit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='permit',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'Can view book'), ('can_create', 'Can create book'), ('can_edit', 'Can edit book'), ('can_delete', 'Can delete book')]},
        ),
    ]
